### Signup
POST http://localhost:3000/auth/signup
Content-Type: application/json

{
  "email": "test@test.com",
  "password": "test"
}

### Signin
POST http://localhost:3000/auth/signin
Content-Type: application/json

{
  "email": "test2@test.com",
  "password": "test"
}

### sign out
POST http://localhost:3000/auth/signout

### Get signed in user
GET http://localhost:3000/auth/whoami

### find one user
GET http://localhost:3000/auth/4

### Find user with emil
GET http://localhost:3000/auth?email=admin@admin.com

### remove user
PATCH  http://localhost:3000/auth/4
Content-Type: application/json

{
  "email": "a@a.com"
}


### remove user
DELETE http://localhost:3000/auth/1
Content-Type: application/json




